title: "JoeKoop.com"
author: "Joe Koop"
description: "Personal website of Joe Koop"
#theme: "minima"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
include:
  - ".well-known"
